# We will train 3 models 
- Facebook bart CNN model
- T5 Small
- Pegasus

and then we'll learn their working from **evaluation comparisons**

In [115]:
# Text Summarization Model are imported from transformers
from transformers import pipeline

# Time Calculated
import time
import tracemalloc

In [116]:
# Sample text for summarization
text = """It's a big week for Apple. Here's what to expect. Apple is expected to make several announcements this week on top of reporting earnings. Greg Joswiak, a senior vice president of marketing at Apple, teased something new for Macs. Its long-awaited Apple Intelligence is expected to launch with software updates. Apple is gearing up for an eventful week. The company is expected to introduce software and hardware updates to its tech lineup, and it's scheduled to report earnings on Thursday. Greg Joswiak, Apple's senior vice president of marketing, told his X followers last Thursday to "Mac" their calendars for a week of announcements from the tech giant. Mac your calendars! We have an exciting week of announcements ahead, starting on Monday morning. Stay tuned… pic. twitter. com/YnoCYkZq6c— Greg Joswiak (@gregjoz) October 24, 2024 Eligible iPhone owners are also expected to gain access to the first round of Apple Intelligence features with the iOS 18. 1 update. Apple first announced its AI plans at the Worldwide Developers Conference in June. The AI tools, compatible with the iPhone 15 Pro and later models, have been highly anticipated. Though Apple hasn't been provided dates for the AI rollout, it's expected to begin this week, and the company has said it will continue "over the course of the next year." Apple didn't immediately respond to a request for comment from Business Insider. Mark Gurman, a tech correspondent at Bloomberg, said on X that Apple would host a "hands on experience" related to the Mac announcement in Los Angeles on Wednesday for media and content creators. Gurman had previously reported that a new Mac lineup would include M4 versions of Apple's iMac, MacBook Pro, and Mac mini. Apple is set to deliver its fiscal fourth-quarter earnings results on Thursday. Apple Intelligence was a major talking point during its third-quarter earnings call in August. CEO Tim Cook told investors at the time that Apple was investing more in its AI efforts. "With Apple Intelligence, we're very excited about the level of value we're going to provide to users," Cook said.
"""

# Model 1: Facebook bart CNN model

In [118]:
def summarize_textM1(text):
    # Load summarization pipeline with BART
    summarizer1 = pipeline("summarization", model="facebook/bart-large-cnn")
    
    # Start measuring time and memory
    tracemalloc.start()
    start_time = time.time()
    
    # Generate summary
    summary_model1 = summarizer1(text, max_length=50, min_length=20, do_sample=False)
    summary1 = summary_model1[0]['summary_text']
    
    # Stop measuring time and memory
    end_time = time.time()
    memory_used = tracemalloc.get_traced_memory()[1] / (1024 * 1024)  # Convert to MB
    tracemalloc.stop()
    
    time_taken = end_time - start_time
    
    return time_taken, memory_used, summary1

In [119]:
# Call function M1
time_taken, memory_used, summary1 = summarize_textM1(text)

Device set to use cpu


In [120]:
# Print results
print(f"Time Taken: {time_taken:.4f} seconds")
print(f"Memory Used: {memory_used:.4f} MB")
print("Summary:", summary1)

Time Taken: 8.5344 seconds
Memory Used: 0.2484 MB
Summary: Apple is set to make several announcements this week. The company is expected to introduce software and hardware updates to its tech lineup. It's also scheduled to report its fiscal fourth-quarter earnings on Thursday.


# Model 2: T5 small

In [122]:
def summarize_textM2(text):
    # Load summarization pipeline with T5
    summarizer2 = pipeline("summarization", model="t5-small")
    
    # Start measuring time and memory
    tracemalloc.start()
    start_time = time.time()
    
    # Generate summary
    summary_model2 = summarizer2(text, max_length=50, min_length=20, do_sample=False)
    summary2 = summary_model2[0]['summary_text']
    
    # Stop measuring time and memory
    end_time = time.time()
    memory_used = tracemalloc.get_traced_memory()[1] / (1024 * 1024)  # Convert to MB
    tracemalloc.stop()
    
    time_taken = end_time - start_time
    
    return time_taken, memory_used, summary2


In [123]:
# Call function M2
time_taken, memory_used, summary2 = summarize_textM2(text)

Device set to use cpu


In [124]:
# Print results
print(f"Time Taken: {time_taken:.4f} seconds")
print(f"Memory Used: {memory_used:.4f} MB")
print("Summary:", summary2)

Time Taken: 3.2109 seconds
Memory Used: 0.2126 MB
Summary: apple is expected to make several announcements this week on top of reporting earnings . it's expected to introduce software and hardware updates to its tech lineup . the company is set to report earnings on Thursday .


# Model 3: Pegasus

In [126]:
def summarize_textM3(text):
    # Load summarization pipeline with PEGASUS
    summarizer3 = pipeline("summarization", model="google/pegasus-xsum")
    
    # Start measuring time and memory
    tracemalloc.start()
    start_time = time.time()
    
    # Generate summary
    summary_model3 = summarizer3(text, max_length=50, min_length=20, do_sample=False)
    summary3 = summary_model3[0]['summary_text']
    
    # Stop measuring time and memory
    end_time = time.time()
    memory_used = tracemalloc.get_traced_memory()[1] / (1024 * 1024)  # Convert to MB
    tracemalloc.stop()
    
    time_taken = end_time - start_time
    
    return time_taken, memory_used, summary3

In [127]:
# Call function M3
time_taken, memory_used, summary3 = summarize_textM3(text)

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-xsum and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Device set to use cpu


In [128]:
# Print results
print(f"Time Taken: {time_taken:.4f} seconds")
print(f"Memory Used: {memory_used:.4f} MB")
print("Summary:", summary3)

Time Taken: 12.5348 seconds
Memory Used: 0.0724 MB
Summary: Apple is expected to launch its long-awaited artificial intelligence tools this week, according to reports.


# Evaluations of Model based on Computations

In [130]:
summaries = [summary1, summary2, summary3]

**1. TF-IDF**

In [132]:
# TF-IDF Dependencies
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [133]:
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(summaries)
similarity_matrix = cosine_similarity(tfidf_matrix)

In [134]:
print("TF-IDF Cosine Similarity:\n", similarity_matrix)

TF-IDF Cosine Similarity:
 [[1.         0.81018523 0.3281629 ]
 [0.81018523 1.         0.31898093]
 [0.3281629  0.31898093 1.        ]]


**2. Bert-Cosine**

In [136]:
# Bert-Cosine Similarity
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [137]:
# Load pre-trained Sentence-BERT model
model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight but effective model

In [138]:
# Convert summaries to embeddings
embeddings = model.encode(summaries)

# Compute cosine similarity
similarity_matrix = cosine_similarity(embeddings)

In [139]:
# Print results
print("Sentence-BERT Cosine Similarity:\n", similarity_matrix)

Sentence-BERT Cosine Similarity:
 [[0.99999994 0.93364614 0.59117126]
 [0.93364614 1.0000001  0.4634985 ]
 [0.59117126 0.4634985  0.9999999 ]]


**3. Word2Vec**

In [141]:
# Word2Vec Dependencies
import gensim
import numpy as np

In [142]:
# Tokenize summaries
tokenized_summaries = [summary.lower().split() for summary in summaries]

In [143]:
# Train Word2Vec model
word2vec_model = gensim.models.Word2Vec(tokenized_summaries, vector_size=100, window=5, min_count=1, sg=0)

In [144]:
# Function to get sentence embeddings by averaging word vectors
def get_sentence_embedding(sentence, model):
    words = sentence.lower().split()
    word_vectors = [model.wv[word] for word in words if word in model.wv]
    return np.mean(word_vectors, axis=0) if word_vectors else np.zeros(model.vector_size)

In [145]:
# Compute sentence embeddings
sentence_embeddings = np.array([get_sentence_embedding(summary, word2vec_model) for summary in summaries])

In [146]:
# Compute cosine similarity
similarity_matrix = cosine_similarity(sentence_embeddings)

In [147]:
print("Word2Vec Cosine Similarity:\n", similarity_matrix)

Word2Vec Cosine Similarity:
 [[0.99999994 0.7808941  0.53935945]
 [0.7808941  1.         0.47915116]
 [0.53935945 0.47915116 1.0000001 ]]
